name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for some coverage actions

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev] -r requirements.txt

    - name: Run Pytest tests
      run: |
        pytest --cov=src --cov-report=xml # Run tests with coverage and generate an XML report
