name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for some coverage actions

    - name: Enable caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: '3.12' # Specify your desired Python version


    - name: Install dependencies
      run: |
        uv pip install -e .[dev] -r requirements.txt

    - name: Run Pytest tests
      run: |
        uv run pytest --cov=src --cov-report=xml # Run tests with coverage and generate an XML report

    - name: Minimize uv cache
      run: |
        uv cache prune --ci
