name: ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for some coverage actions

    - uses: astral-sh/ruff-action@v3
      with:
        src: "./src"
